### ISSUE TITLE
h5py is running against HDF5 1.10.2 when it was built against 1.10.3, this may cause problems

### ISSUE THREAD

**Issue by mwtoews** [conda-forge/h5py-feedstock#39]
I'm seeing a new warning message with both Anaconda2 and Anaconda3 that use this package from conda-forge. Here is the message:
```
Python 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 11:48:23) [MSC v.1900 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.0.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import h5py
C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:72: UserWarning: h5py is running against HDF5 1.10.2 when it was built against 1.10.3, this may cause problems
  '{0}.{1}.{2}'.format(*version.hdf5_built_version_tuple)
```
Other info from anaconada2:
```
>conda list h*5
# packages in environment at C:\ProgramData\Anaconda2:
#
# Name                    Version                   Build  Channel
h5py                      2.8.0            py27hb295e13_3    conda-forge
hdf5                      1.10.2                    vc9_0  [vc9]  conda-forge
```
and anaconda3
```
>conda list h*5
# packages in environment at C:\ProgramData\Anaconda3:
#
# Name                    Version                   Build  Channel
h5py                      2.8.0            py36h54c06b0_3    conda-forge
hdf5                      1.10.2                   vc14_0  [vc14]  conda-forge
```

**Comment by ocefpaf** [comment]
This is the recipe for the `py36h54c06b0_3` version there and `py27hb295e13_3` is similar:

```yaml
# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# C:\projects\h5py-feedstock\recipe, last modified Sat Oct  6 03:20:18 2018
# ------------------------------------------------

package:
    name: h5py
    version: 2.8.0
source:
    sha256: eae41382be28b7264824450ce343dd625f972bedaaa3b0cced284986aabcbaee
    url: https://github.com/h5py/h5py/archive/2.8.0.tar.gz
build:
    number: '3'
    string: py36h54c06b0_3
requirements:
    build:
        - vs2015_win-64 14.0.25123 h17c34da_3
    host:
        - blas 1.0 mkl
        - certifi 2018.8.24 py36_1001
        - cython 0.28.5 py36h6538335_1000
        - hdf5 1.10.2 vc14_0
        - icc_rt 2017.0.4 h97af966_0
        - intel-openmp 2019.0 118
        - m2w64-libwinpthread-git 5.0.0.4634.697f757 2
        - m2w64-pkg-config 0.29.1 2
        - mkl 2019.0 118
        - msys2-conda-epoch 20160418 1
        - numpy 1.11.3 py36h53ece5f_11
        - numpy-base 1.11.3 py36h8128ebf_11
        - pip 18.0 py36_1001
        - pkgconfig 1.3.1 py36_1001
        - python 3.6.6 he025d50_0
        - setuptools 40.4.3 py36_0
        - six 1.11.0 py36_1001
        - vc 14 0
        - vs2015_runtime 14.0.25420 0
        - wheel 0.32.1 py36_0
        - wincertstore 0.2 py36_1002
        - zlib 1.2.11 vc14_0
    run:
        - hdf5 >=1.10.2,<1.10.3.0a0
        - numpy >=1.11.3,<2.0a0
        - pyreadline
        - python >=3.6,<3.7.0a0
        - six
        - vc 14.*
test:
    imports:
        - h5py
about:
    home: http://www.h5py.org/
    license: BSD 3-Clause
    license_file: licenses/license.txt
    summary: Read and write HDF5 files from Python.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - pitrou
        - tacaswell
```

Looks OK to me :-/
